// DOCKER/Mauricio-da-Rosa-Ventura/docker-compose/cenario-2-react-express-postgres/frontend/src/App.jsx
import { useEffect, useState } from "react";

// Componente unico e minimo: so prova, do lado do navegador, que o proxy
// Nginx encaminha "/" para este frontend e "/api/" para a API Express, que
// por sua vez fala com postgres/redis/rabbitmq (ver backend/src/index.js).
// Nenhuma regra de negocio e implementada de proposito - o foco desta
// atividade e a estrutura de containers atras de um proxy reverso.
export default function App() {
  const [status, setStatus] = useState(null);
  const [erro, setErro] = useState(null);

  async function verificar() {
    setErro(null);
    try {
      // caminho relativo: passa pelo mesmo proxy Nginx (porta 8080) que
      // serviu esta pagina, sem precisar saber o host/porta interna da api
      const resp = await fetch("/api/status");
      setStatus(await resp.json());
    } catch (e) {
      setErro(e.message);
    }
  }

  useEffect(() => {
    verificar();
  }, []);

  return (
    <main style={{ fontFamily: "sans-serif", maxWidth: 640, margin: "2rem auto" }}>
      <h1>Cenário 2 — Docker Compose</h1>
      <p>ReactJS + PostgreSQL + Node/Express + Redis + RabbitMQ, atrás de um proxy Nginx.</p>
      <button onClick={verificar}>Testar conexão com a API</button>
      {erro && <p style={{ color: "crimson" }}>Erro: {erro}</p>}
      {status && <pre>{JSON.stringify(status, null, 2)}</pre>}
    </main>
  );
}

// DOCKER/Mauricio-da-Rosa-Ventura/docker-compose/cenario-3-consolidacao/frontend/src/App.vue
<script setup>
import { ref, onMounted } from "vue";

// Frontend minimo do Cenario 3: testa a API (health/status) e permite
// disparar um evento (POST /eventos), que a API grava no Postgres e publica
// no RabbitMQ para o worker processar de forma assincrona.
const API = "http://localhost:3001";

const status = ref(null);
const erro = ref(null);
const ultimoEvento = ref(null);

async function verificarStatus() {
  erro.value = null;
  try {
    const resp = await fetch(`${API}/status`);
    status.value = await resp.json();
  } catch (e) {
    erro.value = e.message;
  }
}

async function dispararEvento() {
  erro.value = null;
  try {
    const resp = await fetch(`${API}/eventos`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ tipo: "evento-de-teste" }),
    });
    ultimoEvento.value = await resp.json();
    await verificarStatus();
  } catch (e) {
    erro.value = e.message;
  }
}

onMounted(verificarStatus);
</script>

<template>
  <main style="font-family: sans-serif; max-width: 640px; margin: 2rem auto">
    <h1>Cenário 3 — Consolidação</h1>
    <p>Vue + Fastify + PostgreSQL + Redis + RabbitMQ + worker dedicado.</p>
    <button @click="verificarStatus">Testar conexão com a API</button>
    <button @click="dispararEvento">Disparar evento (POST /eventos)</button>
    <p v-if="erro" style="color: crimson">Erro: {{ erro }}</p>
    <p v-if="ultimoEvento">Último evento enviado: {{ JSON.stringify(ultimoEvento) }}</p>
    <pre v-if="status">{{ JSON.stringify(status, null, 2) }}</pre>
  </main>
</template>
